### ISSUE TITLE
Safari browser issue

### ISSUE THREAD

**Issue by spfrood** [inland-empire-software-development/main#30] opened 2019-06-19 18:23 UTC
Issue with going to the site https://www.ie-sd.com
Does not happen when going directly to https://ie-sd.com

Screenshot of error attached.
![Screen Shot 2019-06-19 at 11 19 45 AM](https://user-images.githubusercontent.com/8482715/59790361-a3071700-9284-11e9-9c9b-f878a2cca951.png)

**Comment by dhuan008** [comment] 2019-06-19 19:00
Similar issue using Edge.
![Capture](https://user-images.githubusercontent.com/33335681/59791896-edd65e00-9287-11e9-91d6-efc94547cac5.PNG)

And on Firefox for first access
![Capture2](https://user-images.githubusercontent.com/33335681/59792729-b2d52a00-9289-11e9-89c6-25ba3c8b215f.PNG)

**Comment by Holyoke** [comment] 2019-06-21 03:18
I'm not able to reproduce this on a Safari Browser Version 12.1.1 (12607.2.6.1.2), on OSX 10.12.6 (Sierra). I visited https://ie-sd.com and report the project is currently live with no connection warnings.

**Comment by lloan** [comment] 2019-06-21 06:19
If we can get 1 more test that passes, we can close this.

**Comment by Holyoke** [comment] 2019-06-22 18:03
I'm able to reproduce this on the iPhone Safari Browser, iOS 11 but only through clicking a pop-up link within another app. For example, accessing the website through the Slack app by clicking a link - the internal frame browser runs into that connection issue. 

I've collected more certificate information, and I'll post that in the Slack for further discussion. 

![Photo Jun 22, 10 52 02 AM](https://user-images.githubusercontent.com/6300995/59967310-08eddb80-94dd-11e9-9e4c-8847acb59323.png)

**Comment by lloan** [comment] 2019-06-22 19:04
Does the link have www or no www? I know someone pointed out that could be the issue. If so, that's a simple fix via nginx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lloan** [comment] 2019-06-22 22:35
Updating the server at the moment, will then take a look at NGINX / Certbot.

**Comment by lloan** [comment] 2019-06-22 22:44
I went ahead and updated the certificate and the nginx configuration. @Holyoke could you test again - make sure to clear your cache :D - thanks!

**Comment by lloan** [comment] 2019-06-22 23:49
Closing this out as I can't reproduce it. I had two people test this today and they could not reproduce the error either. Reopen this issue if you can reproduce it and provide the URL + screenshot.

Thanks!

**Closed by lloan** 2019-06-22 23:49 UTC
