### ISSUE TITLE
Add support for Safari

### ISSUE THREAD

**Issue by jenlatchman** [inland-empire-software-development/main#137] opened 2019-11-19 08:18 UTC
Margin needed in the success story component
![Screen Shot 2019-11-18 at 11 30 01 PM](https://user-images.githubusercontent.com/57469292/69128793-ed720700-0a61-11ea-9fbd-e7092b747938.png)

**Comment by abowler2** [comment] 2019-11-20 17:34
I was not able to reproduce this on my Macbook or iPhone.  Can you check to see if it is still happening for you?

**Comment by abowler2** [comment] 2019-11-21 03:09
After talking with Jen tonight, it looks like this is an issue with older versions of Safari. There might be a way to add a separate webkit selector to address this.

**Comment by VelazquezLuis** [comment] 2019-11-26 06:03
@jenlatchman hey jen can you find out what version of safari you have? and was it when you were full screen?

**Comment by jenlatchman** [comment] 2019-11-26 06:10
Version 12.1.1 
It fixes once I get to what I think is the mobile size.

**Comment by lloan** [comment] 2020-05-22 02:50
Closing because this is no longer needed. Application is being redesigned and this will be addressed.

**Closed by lloan** 2020-05-22 02:50 UTC
