### ISSUE TITLE
Mobile view nav drawer menu About and Organization do not do anything. 

### ISSUE THREAD

**Issue by erik-sandoval** [inland-empire-software-development/main#109] opened 2019-11-06 00:25 UTC
When I click on it, it does not respond.

**Comment by lloan** [comment] 2019-11-06 01:09
Thanks for reporting @erik-sandoval ! 

Closing this one as its a duplicate of #105 

Take a look at it in case you want to work on it :)

**Closed by lloan** 2019-11-06 01:09 UTC
